### ISSUE TITLE
Compress cached tiles in memory

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/terracotta#116]
We currently run with 500MB of raster cache by default, which fills up very very quickly. We could alleviate this a bit by compressing the tiles before adding them to the cache (and decompress upon reading).

**Comment by mrpgraae** [comment]
That is a really good idea IMO, I have had problems with a gunicorn + tc deployment eating up a lot of memory, due to each worker thread having it's own cache. So anything that optimizes caching would be a good idea I think. I would also expect the overhead of decompressing the tiles to be insignificant compared to network I/O.

**Comment by dionhaefner** [comment]
Yea should be fairly low-hanging. Alternatively we could have another stab at making some driver thread-safe, then you could throw some threads in the mix. Third option could be to leverage an external cache like memcached or redis.

**Comment by mrpgraae** [comment]
Actually, if we are going to start doing sessions for authentication as per #21, we might want to use something like Redis to store the sessions and then we might as well use it for caching too.

**Comment by dionhaefner** [comment]
An external cache would be nice, but would be a lot of work, since we also need to support the corresponding AWS service. So we could do both, in-memory compression for now, and explore some of the more sophisticated options.

**Comment by mrpgraae** [comment]
Yes, it should also be easy to implement the compression, so we should do that as a first go. For the more sophisticated options on Lambda, there's Amazon Elasticache https://aws.amazon.com/elasticache/ which seems to be just a Redis instance managed by AWS.
