### ISSUE TITLE
Database compatibility across versions

### ISSUE THREAD

**Issue by mrpgraae** [DHI-GRAS/terracotta#118]
There is no guarantee that a database created with an older version of Terracotta will work with a newer version. This means that upgrading an existing deployment of Terracotta can be a bit of a pain, since every dataset in the deployment must be re-ingested into a new database.

We could make this a bit easier, by making a `migrate-db` command, which takes an old db and creates a new one by re-ingesting everything using the keys and paths in the old db.
Additionally, we could have an option for simply forcing a version bump in the db without re-ingesting (like `--force-version-bump` or so) for power-users who know that the new version is compatible with their database. This could be nice for large deployments, where re-ingesting everything might take days.

The release notes should also specify whether or not the new version is compatible with databases from the previous version.

**Comment by j08lue** [comment]
If you did switch to sqlalchemy, like you once considered in https://github.com/DHI-GRAS/terracotta/issues/76#issuecomment-428210439, adding migration would be very simple with [alembic](https://github.com/zzzeek/alembic) or so.

**Comment by mrpgraae** [comment]
> 
> 
> If you did switch to sqlalchemy, like you once considered in [#76 (comment)](https://github.com/DHI-GRAS/terracotta/issues/76#issuecomment-428210439), adding migration would be very simple with [alembic](https://github.com/zzzeek/alembic) or so.

I think changes that break backwards compatibility would mostly be changes that require more / different metadata to be present in the db. That would mean re-computing metadata, which means that there probably isn't much to be gained from a migration script vs. just re-ingesting everything.

For changes that just require some kind of structural db change or that can be directly computed from the old database, a migration script could be a fast-path around re-ingesting. But it would mean we would have to write migration scripts for every version change.

**Comment by j08lue** [comment]
> But it would mean we would have to write migration scripts for every version change.

That is what some of these tools do for you, based on the changes you make to your model (specified via ORM).

**Comment by dionhaefner** [comment]
This is indeed a major open question in Terracotta. Let me start by describing how it is currently handled. We currently use semantic versioning (`major.minor.patch`), where `minor` breaks API and database compatibility, and `patch` keeps both. That's why Terracotta currently enforces minor versions to match (both in the driver and in `terracotta connect`). That makes this obsolete:

> The release notes should also specify whether or not the new version is compatible with databases from the previous version.

My hope is that we won't need to touch the database schema for a long time, so it could be ok to keep it this way. Otherwise I agree that we need migration scripts where possible.

On a side note, a re-ingestion script could be as simple as

```python
import terracotta as tc

olddb = tc.get_driver('old.sqlite')
newdb = tc.get_driver('new.sqlite')

with olddb.connect(), newdb.connect():
    for keys, path in olddb.get_datasets():
        new_metadata = newdb.compute_metadata(path, extra_metadata=olddb.get_metadata(keys)['metadata'])
        newdb.insert(keys, path, metadata=new_metadata)
```

**Comment by mrpgraae** [comment]
>Because minor updates always break it

What if new features are implemented that don't break anything, would that always just be a patch or could it be considered a minor version, which then will make the e.g. `terracotta connect` not work, even though no actual breaking changes were made?

>My hope is that we won't need to touch the database schema for a long time, so it could be ok to keep it this way. Otherwise I agree that we need migration scripts where possible.

Yes, but as far as I can see, re-ingesting from the old db, using a script like yours would _always_ work right? Unless a change is made which requires more input from the user, in which case a migration script would not work either. So a migration script would only be useful in order to avoid re-computing metadata, if that is not necessary.

You have a good point that re-ingesting from a database is very easy using the API, so the convenience value of a `migrate-db` command might not be that significant.

**Comment by mrpgraae** [comment]
Thanks for the clarification.

>Yes, part of my point is that migration scripts are probably not particularly useful for us. Incompatibility always means we need to re-compute metadata.

Good, we are on the same page then 😄

**Comment by dionhaefner** [comment]
AFAICT this is not really a major concern for all practical purposes. Feel free to re-open if I'm mistaken.
