### ISSUE TITLE
Explicit Colour Map Returning Transparent Tiles

### ISSUE THREAD

**Issue by vlro** [DHI-GRAS/terracotta#119]
Any request with an explicit colour map returns only transparent tiles. It doesn't seem to matter whether we use rgb tuples, rgba tuples or hex strings.

The issue appeared when upgrading from 0.4 to the newest version  (0.5.1.dev3+geed2b0e).
Example request:

`https://example.com/singleband/key1/key2/preview.png?colormap=explicit&explicit_color_map=%7B%220%22%3A%20%22ff0000ff%22%2C%20%221%22%3A%20%22ffffbeff%22%2C%20%222%22%3A%20%22e1e1e1ff%22%7D`

The URI encoded JSON is:
`{"0": "ff0000ff", "1": "ffffbeff", "2": "e1e1e1ff"}`

**Comment by dionhaefner** [comment]
Can confirm the bug, but don't know how to fix it yet. I'll need to do some testing.

**Comment by mrpgraae** [comment]
I'm looking into this

**Comment by dionhaefner** [comment]
Sorry, got the solution in my sleep :)

**Comment by mrpgraae** [comment]
Yes, just found it myself also 😄

**Comment by dionhaefner** [comment]
You can have the honor to fix the tests :grimacing:

Looks like the recent version of the flake8 plugin is broken.

**Comment by mrpgraae** [comment]
Yes, looks like @j08lue found the issue to be with the pytest-benchmark plugin, so I'm just pinning that to `3.1.1` for now.
