### ISSUE TITLE
test failures - unpin pytest-benchmark

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#123]
Due to this issue https://github.com/ionelmc/pytest-benchmark/issues/145, we currently pin `pytest-benchmarks` to `3.1.1`. We should remove that pin as soon as the fix they pushed is released we verified that it works.

**Comment by dionhaefner** [comment]
pytest-benchmark released version 3.2.2 that shouldn't have this problem. Would you like to test it?
