### ISSUE TITLE
terracotta docker

### ISSUE THREAD

**Issue by glw** [DHI-GRAS/terracotta#129]
Hi

Just thought I would let you know, I have put the latest version of terracotta (no aws cli) in a docker image. You can get it here:
https://hub.docker.com/r/garretw/terracotta
or
https://github.com/glw/terracotta_cog_docker

It's currently using docker's python 3.6 image, so it a bit large on file size. In the future Ill switch images to alpine-python, so that should save a significant amount of memory.

Thanks for your work on terracotta!!

**Comment by dionhaefner** [comment]
Great initiative, thanks!

Is there any particular use case that made you want to use Terracotta from inside Docker?

**Comment by glw** [comment]
Nothing too fancy yet, Docker just helps us install things easier without as much worry. But this will also be the start of our drone imagery viewer - which Im excited about :)

**Comment by CChisuwo** [comment]
Hi! 

I tried pulling the docker image but I keep getting this error below are you aware of this issue or I need to raise an issue  in the repository. 


```
Error response from daemon: manifest for garretw/terracotta:latest not found: manifest unknown: manifest unknown
```

**Comment by glw** [comment]
If I get a chance this week I will try to take a look to find the issue.
