### ISSUE TITLE
Preview app does not support datasets where min == max

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/terracotta#140]
Activating the layer does not work. I get

```
Error: noUiSlider (12.0.0): 'range' 'min' and 'max' cannot be equal.
```

in the JS console. Seems like we will have to catch this case...

**Comment by FrancescoErmini** [comment]
I found this issue using categorical raster with only one label set. E.g max = 1, min = n.a.

**Comment by j08lue** [comment]
Thanks for reporting, @FrancescoErmini. Wonder how best to fix this. I see three options:
1. We try to get this fixed upstream (https://github.com/leongersen/noUiSlider)
2. We patch our copy of the code
3. We branch off on this case before initializing the slider and replace the slider element by something else.

Maybe worth giving 1. a try first? It is a valid edge case for the slider to support, I'd say.

**Comment by dionhaefner** [comment]
4. Catch this case and just use a dummy `min = max - 1`
5. Catch this case and never enable / setup the slider (maybe this is your no. 3)

I suggest 1 if anyone volunteers to do it, otherwise 5.

**Comment by mrpgraae** [comment]
See this issue https://github.com/leongersen/noUiSlider/issues/676 for the upstream maintainers stance on 1.

**Comment by j08lue** [comment]
Bullseye. 5 it is, then. Any of you full-stack pros want to fix it or should I try to find a JS volunteer?

**Comment by mrpgraae** [comment]
I'm assuming this is where the `min == max` branch should be? Anywhere else?
https://github.com/DHI-GRAS/terracotta/blob/3c9feff9910382da1c827f11d8a84e7f08a44970/terracotta/client/static/main.js#L924-L934

**Comment by dionhaefner** [comment]
There and in the corresponding singleband function:

https://github.com/DHI-GRAS/terracotta/blob/3c9feff9910382da1c827f11d8a84e7f08a44970/terracotta/client/static/main.js#L693-L698

I kinda like the proposed solution from the issue:

> I solved this issue externally now. So when the min equals the max value in the range object I check before I initialize the noUiSlider if min == max - if so, I subtract the step value from the min and add the step value to the max. Additionally I set the start and stop value to the initial min/max value and I disable the slider by setting "behaviour" to "fixed".
> 
> That way I get a slider rendered which has its handles fixed to the middle and doesn't to anything than staying there.

**Comment by mrpgraae** [comment]
>I kinda like the proposed solution from the issue

Yup, I started implementing that, but got cold feet since I wasn't sure of what I was doing :smile:

**Comment by dionhaefner** [comment]
Simplest implementation should be something like

```javascript
if (metadata.range[0] == metadata.range[1]) {
 singlebandSlider.noUiSlider.updateOptions({ 
     range: { 
         min: metadata.range[0] - 1, 
         max: metadata.range[1] + 1,
     },
     behaviour: "fixed", 
 }); 
}
```
