### ISSUE TITLE
Fix get_driver typing issue

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#149]
The reason why current builds like https://travis-ci.com/DHI-GRAS/terracotta/builds/117457626 fail:

There is a typing error: `get_driver` accepts `Union[str, Path]` and passes that on to `DriverClass.__init__`, which is fine for `SQLiteDriver` but not for `MySQLDriver`, which only accepts `str`.

**Comment by j08lue** [comment]
I propose we just have all drivers accept `Union[str, Path]` and then they can convert `Path` to `str` internally as a workaround. Not pretty, since `MySQLDriver` will fail e.g. with a Windows `Path`, but it would work.

**Comment by dionhaefner** [comment]
Let’s change the type signature to `str`. People can still pass paths, which will work for the SQLite driver, but the officially supported way is string anyway.

**Comment by dionhaefner** [comment]
The alternative would be to have an `isinstance` check in `get_driver` to make sure no `Path` is passed to a MySQL driver. Whichever you like better.

**Comment by mrpgraae** [comment]
IMO it would be cleanest to just use `str` here.

**Comment by j08lue** [comment]
> Let’s change the type signature to `str`.

You mean the signature of `get_driver`, right? OK with that, too.

**Comment by dionhaefner** [comment]
Yes.
