### ISSUE TITLE
Create sample image catalogue

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/terracotta#152]
For testing, it would be awesome to have a separate repository with (pathological) test images, such as

- some different satellite images, in different formats (GTiff, COG, JP2) and projections
- an image at high latitudes (Greenland / Antarctica), both in the native projection and WGS84
- an image across the date line
- an artificial image with sharp edges to test interpolation.

This would make it much easier for old and new contributors to do quick manual sanity checks.

I could volunteer to assemble some of this catalogue, but I think @j08lue should have most of those already lying around somewhere? :)

**Comment by vincentsarago** [comment]
👍 this would be great. In addition if we can add STAC items it could be almost perfect

**Comment by j08lue** [comment]
Do you want to add them to this repo or have a separate one, like `terracotta-sample-data` or so to keep the clone size down?

**Comment by dionhaefner** [comment]
I’d say separate repo, possibly with LSF. Could you create a repo @j08lue? Doesn’t even need to be Terracotta branded. It could just be a collection of exmple rasters for everyone (we just need to ensure proper attribution of the data).

**Comment by j08lue** [comment]
OK https://github.com/DHI-GRAS/sample-satellite-imagery

**Comment by dionhaefner** [comment]
Closing this in favor of the new repository. We should really crowdsource this. Could be immensely useful for edge-case testing!
