### ISSUE TITLE
CORS for map tiles?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#160]
We currently enable CORS only for `metadata_api`, not for `tile_api` or `spec_api`:

https://github.com/DHI-GRAS/terracotta/blob/3c9feff9910382da1c827f11d8a84e7f08a44970/terracotta/server/flask_api.py#L21

However, we need CORS also for map tiles when using Mapbox GL as a client, because it fetches the data inside the web client, rather than just letting the browser load the images directly, like Leaflet does it.

What is the rationale behind not enabling CORS for all endpoints? And if we were to change that, should we just enable CORS everywhere or make it a configurable option (`CORS=false` or so)?

**Comment by dionhaefner** [comment]
Config sounds good. With CORS enabled globally, anyone can hijack the Terracotta server and request tiles in the backend of their own application, which might get costly. Of course you can still hijack the server in the frontend without CORS, so the only real protection is proper authentication.

**Comment by mrpgraae** [comment]
CORS being configurable, but disabled by default sounds good.

The best option would be to have a whitelist for domains using the [access-control-allow-origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), But I believe that is something that should be configured in the server that is hosting Terracotta (Gunicorn, nginx, etc.).

**Comment by mrpgraae** [comment]
Here is the way to do whitelist certain endpoints and origins for CORS in Flask
(https://flask-cors.readthedocs.io/en/latest/#resource-specific-cors)
```python
app = Flask(__name__)
cors = CORS(app, resources={r"/api/*": {"origins": "*"}})

@app.route("/api/v1/users")
def list_users():
    return "user example"
```

**Comment by j08lue** [comment]
Thanks, @mrpgraae!

> The best option would be to have a whitelist for origins

I wonder what the origin is when we call Terracotta from Mapbox GL in a web map. If I understand things correctly, it is always the browser. Then we cannot whitelist.

I assume that abuse is not something people too often are worried about. And, correct, in that case only auth really protects you.

So how about the following config options:
```toml
TC_ALLOWED_ORIGINS_METADATA="*"
#TC_ALLOWED_ORIGINS_TILES="*"
```
or perhaps `TC_CORS_ALLOWED_ORIGINS_...`? Then users can freely configure the origins for each group of routes. I will have to hard-code the names of the routes, I guess, but that's no big deal. 

Alternatively, we'll just have booleans:

```toml
TC_ENABLE_CORS_METADATA=true
TC_ENABLE_CORS_TILES=false
```

Opinions, @dionhaefner and @mrpgraae? 😸

**Comment by dionhaefner** [comment]
> I wonder what the origin is when we call Terracotta from Mapbox GL in a web map. If I understand things correctly, it is always the browser. Then we cannot whitelist.

It’s not the browser, otherwise CORS wouldn’t apply. CORS is to protect your content from being served under a different hostname. In that case, the whatever the adress bar says when javascript requests tiles should be whitelisted.

If that works, I vote for your first proposal. But I wouldn’t really mind the second one either if you encounter problems.

**Comment by mrpgraae** [comment]
>It’s not the browser, otherwise CORS wouldn’t apply. CORS is to protect your content from being served under a different hostname. In that case, the whatever the adress bar says when javascript requests tiles should be whitelisted.

For example, on Satlas, the origin would be `http://satlas.dk:80` (port can be omitted when it's 80, but just to show that port is also part of the origin). But according to my browser, the TC instance is running on `https://2truhxo59g.execute-api.eu-central-1.amazonaws.com`, so `http://satlas.dk` needs to be in the `access-control-allow-origin` header.

**Comment by mrpgraae** [comment]
First option is good I think :slightly_smiling_face:

**Comment by j08lue** [comment]
> CORS is to protect your content from being served under a different hostname.

I dunno, thought it was to protect the user from getting content from a different source than they think. But whatever. ¯\_(ツ)_/¯

**Comment by dionhaefner** [comment]
Yes, that is the same thing, just from the user perspective :)

You can test whether CORS works by requesting a tile from Javascript. This tool can help:

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2F2truhxo59g.execute-api.eu-central-1.amazonaws.com%2Fproduction%2Frgb%2Fcomposite%2F20180901%2F1%2F9%2F266%2F159.png&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

If you whitelist `test-cors.org`, the request should succeed.
