### ISSUE TITLE
Add perceptually uniform colormaps (colorcet)

### ISSUE THREAD

**Issue by emilhe** [DHI-GRAS/terracotta#162]
I am a aware that custom colormaps can be injected through the API, but i still think that it would be valuable to have a range of perceptually uniform colormaps available as named colormaps. I would argue, that in the majority of map visualizations, perceptually uniform colormaps should be preferred, and hence they should be available "as default". It seems that in Python, the preferred collection is colorcet,

https://colorcet.holoviz.org/

I am not sure about the naming scheme, the simplest option would probably be to keep everything else as-as and just add new schemes of the form "colorcet.rainbow" for the rainbow from colorcet. I guess the implementation would be fairly simple. I could try myself, if there are no objections towards the feature itself.

**Comment by dionhaefner** [comment]
I note the recent requests for more colormap choices, and I'm thinking about a clean solution.

In the meantime, it might be worth noting that the following build-in colormaps are perceptually uniform:

- `viridis`
- `plasma`
- `inferno`
- `magma`
- `cividis`

([see here](https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html))

**Comment by emilhe** [comment]
Thanks for the update! Yes, it's correct that matplotlib has a few options. However, there are not that many - and i like some of the ones from colorcet better. I will stay tuned for further developments :)

**Comment by j08lue** [comment]
> and i like some of the ones from colorcet better

That is exactly why we make the selection of color maps extendable - everyone has different preferences. 😄 We'll think of something very soon.

**Comment by emilhe** [comment]
@j08lue Haha, as i was writing that sentence i kind of realized that making the selection of color maps extendable would be the right way to go rather than simply adding colorcet. I'll monitor the progress :)

**Comment by dionhaefner** [comment]
This is possible now with the new custom colormap feature. Just dump them into a folder in the right format and point terracotta to it via the `TC_EXTRA_CMAP_FOLDER` envvar ([see the tutorial here](https://terracotta-python.readthedocs.io/en/latest/tutorials/custom-colormaps.html)).
