### ISSUE TITLE
Build docs and publish to PyPI with Travis?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#170]
Is this worth the effort?

* Build and push docs with Travis: https://sphinxtechnicalwriting.readthedocs.io/en/latest/cd/config-travis.html
* Publish tagged releases to PyPI: https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags

**Comment by dionhaefner** [comment]
I'm all up for the PyPI upload, but building the docs via readthedocs directly works just fine, and I don't see the point of complicating that.
