### ISSUE TITLE
Infinite loading of tif and sqlite file in 0.6.1.dev28+g45e4ff0 build

### ISSUE THREAD

**Issue by laxnpander** [DHI-GRAS/terracotta#177]
Hey hey,

my loading issue didn't resolve. The terracotta viewer seems to be loading forever when loading my .tif file. It was an unoptimized tif, so I decided to use the tools to create the optimized one.

The files:
https://cloudstorage.tu-braunschweig.de/getlink/fi3FfLkzcfvrUxU48HVC6rRC/edemissen.sqlite
https://cloudstorage.tu-braunschweig.de/getlink/fi6bqLbn9Wk4kE8PFKCyGWKb/edemissen.tif

Output of my server:
`127.0.0.1 - - [23/Jun/2020 17:03:05] "GET /keys HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:05] "GET /swagger.json HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=greys_r&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=viridis&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=rdbu_r&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=bugn&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=ylgn&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=magma&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=gist_earth&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /colormap?colormap=ocean&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /keys HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /datasets?limit=1000&page=0 HTTP/1.1" 200 -
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET /metadata/edemissen HTTP/1.1" 200 -`

Output of my viewer:
`Opening in existing browser session.
[0623/170307.452728:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
127.0.0.1 - - [23/Jun/2020 17:03:07] "GET / HTTP/1.1" 200 -
`

Did I miss something?

Thanks for the help and best regards,
Alex

**Comment by dionhaefner** [comment]
Can you display the image directly?

I.e., browse to

```
http://localhost:5000/singleband/edmissen/preview.png
````

**Comment by laxnpander** [comment]
Nope:
`{"message":"No dataset found for given keys ('edmissen',)"}`

Server response:
`127.0.0.1 - - [23/Jun/2020 17:16:36] "GET /singleband/edmissen/preview.png HTTP/1.1" 404 -
127.0.0.1 - - [23/Jun/2020 17:16:36] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [23/Jun/2020 17:16:46] "GET /singleband/edmissen/preview.png HTTP/1.1" 404 -
`

**Comment by dionhaefner** [comment]
Sorry, spelled your file name wrong. It's

```
http://localhost:5000/singleband/edemissen/preview.png
```

**Comment by laxnpander** [comment]
@dionhaefner: Ah jeah, this is working. Sorry I didn't check the spelling. However, viewer is still loading.

**Comment by dionhaefner** [comment]
Are there any errors in the Javascript console in the browser window with the viewer?

It seems like it's not really loading, just got an unexpected response so the frontend crashed.

**Comment by dionhaefner** [comment]
In case you haven't already, make sure to restart both server and client (terracotta serve / terracotta connect) after updating Terracotta.

**Comment by laxnpander** [comment]
Yes, console throws the following error:
`Uncaught (in promise) TypeError: Cannot read property 'join' of undefined
    at updateColormap (main.js:593)
    at initUI (main.js:344)
    at main.js:1287`

**Comment by laxnpander** [comment]
@dionhaefner: Good news, it is miraculously working today! So maybe a complete reboot did the job? Anyway, thanks for your help! Again, great job with the software and documentation.
