### ISSUE TITLE
Custom discrete colormaps for float data ranges

### ISSUE THREAD

**Issue by abhi1301** [DHI-GRAS/terracotta#183]
How can I generate custom colormap (in .npy file) for some discrete float values and their corresponding color values of my choice? For example, the following value ranges and their respective colors for a _NDVI_ raster:
**_-1.0 to 0.1 : #b17855
0.1 to 0.2 : #efe8c1
0.2 to 0.3 : #e5dca5
0.3 to 0.4 : #d3df97
0.4 to 0.5 : #a7cf76
0.5 to 0.6 : #78b164
0.6 to 0.7 : #389668
0.7 to 0.8 : #389668
0.8 to 0.9 : #095e3c
0.9 to 1.0 : #023c25_**
I read [this](https://terracotta-python.readthedocs.io/en/latest/tutorials/custom-colormaps.html) tutorial, but couldn't understand how to generate an array of shape **(255, 4)** for these values. 
In matplotlib I could have used [BoundaryNorm](https://matplotlib.org/tutorials/colors/colormapnorms.html#discrete-bounds) for normalization, but that too is only applied while plotting, but to be used in TC, it's needed to be (255,4) shaped array-colormap that has this normalisation pre-applied. Please help!

**Comment by dionhaefner** [comment]
As I see it you have essentially two options:

### 1. Pre-process your raster files and convert them to a categorical format that corresponds to your bins

I.e., convert all values from -1 to 0.1 to `0`, from 0.1 to 0.2 to `1`, and so on. Then, [you can serve them up as categorical rasters](https://terracotta-python.readthedocs.io/en/latest/tutorials/categorical.html) which makes it easy to specify your color mapping via `explicit_color_map`.

### 2. Create a custom color map and use `stretch_range` to query your tiles

This is how I would create the color map:

```python
import numpy as np

COLOR_RANGES = {
    (-1.0, 0.1): 'b17855',
    (0.1, 0.2): 'efe8c1',
    (0.2, 0.3): 'e5dca5',
    (0.3, 0.4): 'd3df97',
    (0.4, 0.5): 'a7cf76',
    (0.5, 0.6): '78b164',
    (0.6, 0.7): '389668',
    (0.7, 0.8): '389668',
    (0.8, 0.9): '095e3c',
    (0.9, 1.0): '023c25',
}

def hex_to_rgba(hexstr):
    return (
        int(hexstr[0:2], 16),
        int(hexstr[2:4], 16),
        int(hexstr[4:6], 16),
        255
    )


cmap_range = np.linspace(-1, 1, 255)
cmap_out = np.empty((255, 4), dtype='uint8')

for (rmin, rmax), hexstr in COLOR_RANGES.items():
    cmap_out[(cmap_range >= rmin) & (cmap_range <= rmax)] = hex_to_rgba(hexstr)

np.save('mycmap.npy', cmap_out)
```

This gives a colormap that looks like this:

![cbar](https://user-images.githubusercontent.com/11994217/88905960-2bf9cb80-d257-11ea-941b-6adba62d92d7.png)


Then, you can register the custom colormap as in the guide you linked. When you query tiles with this colormap, you need to remember to apply the appropriate stretching:

```
http://example.com/singleband/<...>.png?colormap=mycmap&stretch_range=[-1,1]
```

You can double-check via the `/colormap` command:

```
http://example.com/colormap?colormap=mycmap&stretch_range=[-1,1]
```

Hope this helps!

**Comment by abhi1301** [comment]
Yes it works. Thanks a lot.
