### ISSUE TITLE
XYZ tiles of a given Polygon from a large raster tile

### ISSUE THREAD

**Issue by abhi1301** [DHI-GRAS/terracotta#186]
Is there a way or a workaround with terracotta that can help me serve XYZ tiles of a given polygon from a large tile? 
So the case is, I have a large tile but I want only a polygon section of it to be served, rest be masked out invalid, dynamically? I'm using Leaflet maps to visualise the raster tiles.

**Comment by dionhaefner** [comment]
Not really.

Do you know your polygons in advance or are they generated dynamically?

**Comment by j08lue** [comment]
If the polygons are dynamic, the only way I can see would be for you to fork Terracotta and add this custom functionality to the routes as an additional query parameter. From there on it might be an easy job to add the masking of the window-read tile data with [`rasterio.features.geometry_mask`](https://rasterio.readthedocs.io/en/latest/api/rasterio.features.html#rasterio.features.geometry_mask).

**Comment by dionhaefner** [comment]
A simpler solution might be to do the masking client-side. This leaflet plugin looks promising:

https://github.com/aparshin/leaflet-boundary-canvas

**Comment by abhi1301** [comment]
>Do you know your polygons in advance or are they generated dynamically?
Yes, I have the polygons stored in another database. But only the polygon boundaries not rasters.

> A simpler solution might be to do the masking client-side. This leaflet plugin looks promising:
> 
> https://github.com/aparshin/leaflet-boundary-canvas

Yes this looks good only if it has to be served in browser but I also need an API that returns the masked XYZ tiles so I have to achieve this in the server side.

**Comment by dionhaefner** [comment]
Then I'm afraid there is nothing built-in to help you. As @j08lue suggested, you can extend Terracotta by adding something like `clip_polygon` as a route parameter, which then parses the given polygon and applies it as a mask. Then, you could do

```
example.com/singleband/.../{x}/{y}/{z}.png?clip_path=...
```

when sending your requests.

If you decide to do this, it could be valuable to merge this into back into Terracota.

**Comment by abhi1301** [comment]
> As @j08lue suggested, you can extend Terracotta by adding something like clip_polygon as a route parameter, which then parses the given polygon and applies it as a mask.

Yes I could do this, but I need help with two things:
1. If I send the polygon in the URL, like _clip_path=..._ , wouldn't that make my request URL huge when after URI encoding, as all points are  floating point numbers.
2. `rasterio.features.geometry_mask`  this would give me the mask for the raster level, but the operations are at the XYZ tile level in Terracotta, right?, so how do I fetch the corresponding XYZ mask matrix ( ndarray) from it to apply on my XYZ tile (ndarray) from the raster?

**Comment by dionhaefner** [comment]
1. Yes, this might be infeasible with complicated polygons. You could try and base64 encode it to save some space, but you will still run out for complicated geometries. I think in this case you would have to supply a link to a geojson file instead that Terracotta can read.

2. Is easier to solve, just use the transform of the tile instead of the whole raster. I.e., use `vrt.transform` where `vrt` is defined here: https://github.com/DHI-GRAS/terracotta/blob/5776df9a58cd47b4bf0fcb29070ff40ecdf41d98/terracotta/drivers/raster_base.py#L488-L494
This might involve some more fiddling with the window and out_shape, but I could help when you're at that point.

**Comment by abhi1301** [comment]
Thanks for the pointers.
>Yes, this might be infeasible with complicated polygons. You could try and base64 encode it to save some space, but you will still run out for complicated geometries. I think in this case you would have to supply a link to a geojson file instead that Terracotta can read.

1. I can use json payload for the polygon with the request and parse at the server, instead of just adding the whole polygon in the URL. I have tried this, it works.
```
from shapely.geometry import Polygon
content = request.json
poly = Polygon(content["polygon"])
```

> just use the transform of the tile instead of the whole raster.

2. I'll try what you've suggested and update here, or ask my query if stuck somewhere, regarding the fiddlings you mentioned.

**Comment by dionhaefner** [comment]
You are using GET requests to fetch tiles, which should not have a request body. You can of course do this for your personal use, but then we won't be able to merge that into TC (which is fine, just a heads-up).

**Comment by j08lue** [comment]
Too complex polygons will cause the calls to be slow. 

If you can do with the 2048 characters you have on the URL with a GET request, you get about 100 x,y vertices of 8 characters or less, which corresponds to meter-centimeter precision in lat/lon. You could use the [OpenSearch Geo extension](https://www.ogc.org/standards/opensearchgeo) way of specifying a polygon (`x,y,x,y,x,y,x,y,...`).

And yes, get the transform from the tile VRT to feed to `geometry_mask`.

**Comment by emilhe** [comment]
If the polygons are static, another option would be to create a Boolean mask in a pre processing step. While the pre processing can take some time, the requests remain performant. I have previously used this approach for some tiles that were only meaningful onshore.

**Comment by j08lue** [comment]
Thanks for sharing your experience and solution for static masks, @emilhe.

Boolean masks created dynamically could also be cached. With compression, the files are tiny. But hard to share efficiently among Lambda instances...

**Comment by dionhaefner** [comment]
Looks stale to me. Feel free to reopen if this is still relevant.

**Comment by rumski20** [comment]
I'm interested in this functionality. Did @abhi1301 or @emilhe or anyone ever successfully get something up and running?

**Comment by emilhe** [comment]
I ended up using Boolean masks. It worked well, but with the limitations that the polygons must be static.

**Comment by rumski20** [comment]
Okay, thanks. I would need to be able to handle dynamic masks via API routing like @dionhaefner suggested here.

> Then I'm afraid there is nothing built-in to help you. As @j08lue suggested, you can extend Terracotta by adding something like `clip_polygon` as a route parameter, which then parses the given polygon and applies it as a mask. Then, you could do
> 
> ```
> example.com/singleband/.../{x}/{y}/{z}.png?clip_path=...
> ```
> 
> when sending your requests.
