### ISSUE TITLE
Can't connect to MySQL server if password contains '#' character

### ISSUE THREAD

**Issue by abhi1301** [DHI-GRAS/terracotta#187]
`terracotta.get_driver(mysql_path)`

Fails when _mysql_path_ contains '#' in any part. It's actually because of  `urllib.parse` , which fails to parse the URL components if any of the component has '#' in it. There may be other special characters too causing the issue. The password part of the URL has high probability of having these characters. My example : 
```
mysql_path = 'mysql://root:admin#!@123@localhost:3306/db'
```
_Also if you move the '#' around in the password itself, the parsing result is different and hence the errors too_

I solved it by using `quote/unquote` of `urllib.parse` : 
`mysql_path = 'mysql://root:'+ quote('admin#!@123') + '@localhost:3306/db'`

And changed 
https://github.com/DHI-GRAS/terracotta/blob/5776df9a58cd47b4bf0fcb29070ff40ecdf41d98/terracotta/drivers/mysql.py#L118

`password=urlparse.unquote(con_params.password) if con_params.password else None,`

Is this solution right way to handle the issue?

**Comment by dionhaefner** [comment]
Ah, that's not good. Your workaround is OK but a bit awkward.

There should be another way to set MySQL credentials. The case above is fine for simple one-offs, but having the password part of the path is just not great...

**Comment by j08lue** [comment]
When/where does the database path (in your case MySQL connection string) get passed to `urllib.parse`?

> There should be another way to set MySQL credentials. The case above is fine for simple one-offs, but having the password part of the path is just not great...

Connection strings that contain all secrets are pretty standard, I think. And nothing too terrible about that - as long as they are treated correctly.

**Comment by abhi1301** [comment]
@j08lue 
> When/where does the database path (in your case MySQL connection string) get passed to `urllib.parse`?
> 
I just pass the whole URL to `terracotta.get_driver()` which uses `urllib.parse` to extract out the components from URL that finally  is passed to `pymysql.connect(..)`
And I call  `terracotta.get_driver()` in my script to initialize to get a connection to my database, is there any other way too to get the db connection? Because [here ](https://terracotta-python.readthedocs.io/en/latest/api.html#mysql-driver) it states that it's only the way to initialise a db connection.

In case of a server deployment, this URL has to be set to **TC_DRIVER_PATH** environment variable, as stated [here](https://terracotta-python.readthedocs.io/en/latest/tutorials/wsgi.html#systemd), right?

**Comment by j08lue** [comment]
Yes, you are doing everything right.

In this case, I think we should change the code in `get_driver` to handle the different types driver paths better and not pass database URIs to `urllib.parse`.

**Comment by j08lue** [comment]
Yes, you are doing everything right.

In this case, I think we should change the code in `get_driver` to handle the different types driver paths better and not pass database URIs to `urllib.parse`.

**Comment by abhi1301** [comment]
@dionhaefner 

> There should be another way to set MySQL credentials. The case above is fine for simple one-offs, but having the password part of the path is just not great...

To get a connection to my db I have to go through `terracotta.get_driver()` which will lead to `urllib.parse`, how else will `pymysql.connect(..)` get the credentials for a connection. The other way I can see is to have a custom parsing or ditch parsing and provide the credentials from other source (like env variables, config file, etc) directly to `pymysql.connect(..)` .

**Comment by dionhaefner** [comment]
Yes I was thinking of a config variable for username and password.

> In this case, I think we should change the code in get_driver to handle the different types driver paths better and not pass database URIs to urllib.parse.

I don't see how that is possible. How do you treat ambiguities like this?

```
mysql_path = 'mysql://root:admin#!@123@localhost:3306/db'
```

What is the password? `admin#!` or `admin#!@123`?

**Comment by abhi1301** [comment]
> What is the password? `admin#!` or `admin#!@123`?

I don't  know how, but `urllib.parse` was able to parse properly without '#', means '@' created no issue for it, for example if password was _admin!@123_ , parsing works fine. But I get your point on how to treat ambiguities if we have to handle these cases on our own?

**Comment by dionhaefner** [comment]
Different example then: password is `mysql://root:admin#!@123@localhost:3306/db`

```
mysql_path = 'mysql://root:mysql://root:admin#!@123@localhost:3306/db@localhost:3306/db'
```

💫

**Comment by abhi1301** [comment]
> Maybe there is a way to fix this by arguing with the allowed character set of each entity (usernames must be alphanumeric, hostnames US ASCII, ...), but I don't want to be responsible for finding all the edge cases.

Well I looked into the legal characters for username, it seems any ASCII character is allowed, so if there is a colon in the username, it's ambiguous to differentiate. I tried out some DNS parsers, they all fail. They all assume user to handle the quote/unquote for special cases. But if we are not doing that, I think only choice left is to use env variables.

**Comment by dionhaefner** [comment]
Thanks for looking into it, that's what I suspected. So we have these possible fixes:

1. Apply `urlparse.unquote` to username and password in the driver and document that these have to be quoted. This breaks existing code that relies on using a password with benign special characters (such as `!`).

2. Leave path parsing as it is, but introduce a config variable for credentials that people can use if they don't want to / can't assemble a path containing all information.

WDYT? 1, 2, or both?

**Comment by abhi1301** [comment]
> 1. Apply `urlparse.unquote` to username and password in the driver and document that these have to be quoted. This breaks existing code that relies on using a password with benign special characters (such as `!`).'

Well the good thing with  `urlparse.unquote` is that, it will return the exact same text even if it was unquoted. So, if a password had '!' (say admin!@123 ) and was sent in URL unquoted, after parsing when password is passed to unquote, it won't be an error. So no exisiting codes gonna break.
But problem with this approach would be that in case of server deployment, user would have to generate a quoted URL to put it in the **TC_DRIVER_PATH** environment variable. That doesn't seem much user friendly.

> 2. Leave path parsing as it is, but introduce a config variable for credentials that people can use if they don't want to / can't assemble a path containing all information.

This seems easy to use, user doesn't have to worry about generating quoted URL, he can just put it in the config variable as it is. Though this would need change in documentation or a changelog.

So. it's only the question of whether we want to save user the overhead of generating a quoted URL or not?

**Comment by dionhaefner** [comment]
Config variables incoming in #188.
