### ISSUE TITLE
Add option to skip existing datasets when ingesting

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#191]
This picks up from the discussion in https://github.com/DHI-GRAS/terracotta/issues/190#issuecomment-785040789.

You can already get the existing datasets (keys and paths) with 

```python
import terracotta
driver = terracotta.get_driver(DB_PATH)
existing_datasets = driver.get_datasets()
```

So it is just about adding a line somewhere below
https://github.com/DHI-GRAS/terracotta/blob/018c4f7a059086e0eee6f923370b7a03cd8ff70a/terracotta/scripts/ingest.py#L69-L71 
that filters out the existing datasets, if a CLI flag is set.

I can fix this one, unless you are already on it, @dionhaefner? 😉

**Comment by dionhaefner** [comment]
It's all yours :)
