### ISSUE TITLE
Rewrite TC preview app

### ISSUE THREAD

**Issue by bertearazvan** [DHI-GRAS/terracotta#195]
For a better UI, maintainability, and consistency, the TC preview app can be re-written in React and TS.

The interface can be similar to the apps we keep building such as [satlas.dk](satlas.dk) or [urban.satlas.dk](urban.satlas.dk).

**Comment by j08lue** [comment]
Another motivation for this is that a modern preview app based on something as widely used as Create React App can serve as resource for web devs who want to integrate Terracotta-hosted map tiles in their projects.
