### ISSUE TITLE
Ngnix not forwarding to gunicorn

### ISSUE THREAD

**Issue by cursorcl** [DHI-GRAS/terracotta#198]
Hi
I tried to make the secuence i your tutorial (https://terracotta-python.readthedocs.io/en/latest/tutorials/wsgi.html)  without use conda, only the next steps.

My first steps are:
sudo apt-get install ngnix
sudo pip install terracotta[recommended]

then I apply your steps

$ sudo apt install build-essential gdal-bin libgdal-dev
$ pip install cython

$ cd /path/to/terracotta
$ pip install -e .

$ pip install gunicorn

But i don't know where is /path/to/terracotta, I supose is /usr/local/lib/python3.8/dist-packages/terracotta.
In this directory when I run "pip install -e .", but  the system say:
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /usr/local/lib/python3.8/dist-packages/terracotta

Finally I make all the next steps, but Ngnix not forwading the requests.

Thanks

**Comment by dionhaefner** [comment]
The tutorial assumes that you have cloned the Terracotta repository. If you already installed via pip then the `pip install -e` part isn't necessary.

As to why it doesn't work for you, you'll need to be more specific.

**Comment by j08lue** [comment]
We currently have several running instances with Terracotta hosted as indicated in our recipe. Should work more or less out of the box. Please provide details, perhaps we can help.

**Comment by dionhaefner** [comment]
Looks stale to me. Feel free to reopen if this is still relevant.
