### ISSUE TITLE
Migrate CI from Travis to GitHub Actions?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#204]
Travis has served us well and it there are no indications that this would stop soon. But most new projects just use GitHub actions and many old migrate, due to the ease of having it all in one UI. Should we also make the switch?

Should be very easy to do...

What do you think, @dionhaefner?

**Comment by dionhaefner** [comment]
Yes. I was also annoyed that travis-ci.org is shutting down, so I'm switching over my repositories, too.

**Comment by j08lue** [comment]
Cool. Do you already have a setup you are happy with that we can adapt? I do not have any yet that includes mypy or benchmarks.

**Comment by dionhaefner** [comment]
Travis is dead. We need working tests ASAP - before that we can't merge any PRs.
