### ISSUE TITLE
/compute transparent pixel, np.nan instead of zero

### ISSUE THREAD

**Issue by chapmanjacobd** [DHI-GRAS/terracotta#221]
Looking over the [expression parser](https://github.com/DHI-GRAS/terracotta/blob/160f361ca602953b6a56a3bb23caee96d93cdab6/terracotta/expressions.py#L48) I'm not sure if requesting nan squares is possible.

```
v1 * (v1 >= {filter_slider1[0]}) * (v1 <= {filter_slider1[1]})
```

This works great in general but I'm wondering if it would be possible to show a transparent pixel if the expression evaluates to 0.

in pseudo-code:
```
f"v1 if (v1 >= {filter_slider1[0]}) * (v1 <= {filter_slider1[1]}) else np.nan"
```

**Comment by j08lue** [comment]
Nice case, @chapmanjacobd.

Maybe we could make this possible by adding a parameter that lets you specify a NaN / transparent value and mask with that after the expression got evaluated. By default, this could be the raster NaN value.

**Comment by dionhaefner** [comment]
Now that #222 is merged, both invalid values (`nan` / `inf`) and masked values will be transparent. Most of the `np.ma.masked_*` functions are now allowed in expressions.

So your expression should reduce to a one-liner:

```python
masked_outside(v1, lower, upper)
```

Could you try this and report back?

**Comment by chapmanjacobd** [comment]
works great!!
![image](https://user-images.githubusercontent.com/7908073/124940340-848d2900-dfcf-11eb-93b9-b7c3a0a57079.png)
