### ISSUE TITLE
/compute combining masks

### ISSUE THREAD

**Issue by chapmanjacobd** [DHI-GRAS/terracotta#223]
I'm wondering what the syntax would be for this scenario:

I would like to show the v1 values for pixels which are not masked out by v1_filter or v2_filter.

```py
expr1 = f"masked_outside(v1, {filter_slider1[0]}, {filter_slider1[1]})"
expr2 = f"masked_outside(v2, {filter_slider2[0]}, {filter_slider2[1]})"
compute_expr = f"({expr1}) + ({expr2})"
```

Instead of `+` could I have something like this?

```py
np.ma.array(v1, mask=np.logical_and(expr1.mask,expr2.mask))
```

**Comment by dionhaefner** [comment]
OK, I also added `getmask` and `setmask` operators:

```python
setmask(v1, getmask(expr1) & getmask(expr2))
```
