### ISSUE TITLE
Error when starting "terracotta serve"

### ISSUE THREAD

**Issue by monkknacky** [DHI-GRAS/terracotta#232]
I tried with multiple rasters first, then limited to one COG file, same result. I used the optimized rasters from terracotta to create this file. I also tried YYYYMMDD format for date, and DDMMYYYY.

The filename={date}_{band}.tif

terracotta version = 0.7.2
OS=ubuntu 21.04
cli= terracotta serve -r {date}_{band}.tif 

```
Ingesting raster files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2755.78it/s]

 [-] Uncaught exception!
Traceback (most recent call last):
  File "/home/kris/anaconda3/lib/python3.8/site-packages/terracotta/scripts/cli.py", line 52, in entrypoint
    cli(obj={})
  File "/home/kris/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kris/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/terracotta/scripts/serve.py", line 104, in serve
    server_app = create_app(debug=debug, profile=profile)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/terracotta/server/flask_api.py", line 104, in create_app
    SPEC.path(view=terracotta.server.datasets.get_datasets)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/core.py", line 452, in path
    plugin.operation_helper(path=path, operations=operations, **kwargs)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/__init__.py", line 201, in operation_helper
    self.resolver.resolve_operations(operations)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 26, in resolve_operations
    operation["parameters"] = self.resolve_parameters(
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 147, in resolve_parameters
    resolved += self.converter.schema2parameters(
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/openapi.py", line 129, in schema2parameters
    return [
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/openapi.py", line 130, in <listcomp>
    self._field2parameter(
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/openapi.py", line 151, in _field2parameter
    prop = self.field2property(field)
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/field_converter.py", line 172, in field2property
    ret.update(attr_func(field, ret=ret))
  File "/home/kris/anaconda3/lib/python3.8/site-packages/apispec/ext/marshmallow/field_converter.py", line 219, in field2default
    default = field.load_default
AttributeError: 'Integer' object has no attribute 'load_default'
```

gdalinfo:
```
Driver: GTiff/GeoTIFF
Files: 01052021_1.tif
Size is 8282, 7284
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (13.338005675549827,53.242068911423075)
Pixel Size = (0.000179663056824,-0.000179663056824)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  13.3380057,  53.2420689) ( 13d20'16.82"E, 53d14'31.45"N)
Lower Left  (  13.3380057,  51.9334032) ( 13d20'16.82"E, 51d56' 0.25"N)
Upper Right (  14.8259751,  53.2420689) ( 14d49'33.51"E, 53d14'31.45"N)
Lower Right (  14.8259751,  51.9334032) ( 14d49'33.51"E, 51d56' 0.25"N)
Center      (  14.0819904,  52.5877361) ( 14d 4'55.17"E, 52d35'15.85"N)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  Minimum=0.000, Maximum=0.595, Mean=0.219, StdDev=0.027
  NoData Value=-9999
  Overviews: 4141x3642, 2071x1821, 1036x911, 518x456, 259x228
  Mask Flags: PER_DATASET 
  Overviews of mask band: 4141x3642, 2071x1821, 1036x911, 518x456, 259x228
  Metadata:
    STATISTICS_MAXIMUM=0.59531110525131
    STATISTICS_MEAN=0.21883171776486
    STATISTICS_MINIMUM=6.0282647609711e-05
    STATISTICS_STDDEV=0.027083735647097
    STATISTICS_VALID_PERCENT=15.44
```

**Comment by dionhaefner** [comment]
This looks like a version conflict to me. Could you please post the output of `pip freeze`?

**Comment by monkknacky** [comment]
aenum==3.1.0
affine==2.3.0
aiofiles==0.5.0
aiohttp==3.7.4
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.10.0
anaconda-project==0.8.3
aniso8601==7.0.0
AnyQt @ file:///home/conda/feedstock_root/build_artifacts/anyqt_1603277375561/work
apispec==5.1.0
apispec-webframeworks==0.5.2
appdirs==1.4.4
argcomplete==1.12.3
argh==0.26.2
argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1596828493937/work
asciitree==0.3.3
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///tmp/build/80754af9/astroid_1592495912941/work
astropy==4.0.2
async-exit-stack==1.0.1
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==20.3.0
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
Babel @ file:///tmp/build/80754af9/babel_1605108370292/work
backcall==0.2.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
baycomp==1.0.2
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1601745390275/work
bitarray @ file:///tmp/build/80754af9/bitarray_1605065113847/work
bkcharts==0.2
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
blinker==1.4
bokeh @ file:///tmp/build/80754af9/bokeh_1603297833684/work
boto==2.49.0
boto3==1.17.98
botocore==1.20.98
Bottleneck==1.3.2
branca==0.4.2
brotlipy==0.7.0
CacheControl==0.12.6
cachetools==4.2.2
Cartopy==0.18.0
certifi==2020.6.20
cffi @ file:///tmp/build/80754af9/cffi_1600699146221/work
cftime==1.3.1
chardet==3.0.4
click==7.1.2
click-plugins==1.1.1
cligj==0.7.1
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1598400192773/work
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1603211150991/work
colorcet==2.0.6
colorlog==5.0.1
commonmark==0.9.1
conda==4.10.1
conda-build==3.20.5
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1602876795040/work
conda-verify==3.4.2
ConfigArgParse==1.4.1
contextlib2==0.6.0.post1
crick==0.0.3
cryptography @ file:///tmp/build/80754af9/cryptography_1601046815590/work
cycler==0.10.0
Cython @ file:///tmp/build/80754af9/cython_1594831566883/work
cytoolz==0.11.0
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1602029610262/work
dask-gateway==0.9.0
dataclasses-json==0.5.4
datashader==0.12.0
datashape==0.5.2
decorator==4.4.2
defusedxml==0.6.0
Deprecated==1.2.12
dictdiffer==0.8.0
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
dill==0.3.4
distributed @ file:///tmp/build/80754af9/distributed_1605066520644/work
dnspython==1.16.0
docutils==0.16
ecdsa==0.13
email-validator==1.1.2
entrypoints==0.3
et-xmlfile==1.0.1
eventlet==0.31.1
fastapi==0.63.0
fastcache==1.1.0
fasteners==0.16
fiftyone==0.11.1
fiftyone-brain==0.6.1
fiftyone-db==0.2.1
fiftyone-desktop==0.13.4
filelock==3.0.12
Fiona==1.8.18
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1601874335748/work
Flask==1.1.2
Flask-BasicAuth==0.2.0
Flask-Cors==3.0.10
fpdf==1.7.2
fsspec==0.8.7
future==0.18.2
GDAL==3.1.3
gdal2mbtiles==2.1.2
gdal2tiles==0.1.9
geojson==2.5.0
geomet==0.3.0
geopandas==0.9.0
geoviews==1.8.1
gevent @ file:///tmp/build/80754af9/gevent_1601397537062/work
geventhttpclient==1.4.4
glob2==0.7
gmpy2==2.0.8
graphene==2.1.8
graphql-core==2.3.2
graphql-relay==2.0.1
greenlet==1.1.0
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1609518832927/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1610643780568/work
h5py==2.10.0
HeapDict==1.0.1
holoviews==1.14.1
hpack==4.0.0
html2text==2020.1.16
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
http-ece==1.1.0
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1611864786085/work
httptools==0.1.1
httpx @ file:///home/conda/feedstock_root/build_artifacts/httpx_1614586839586/work
husqvarna-automower==2021.3.2
hvplot==0.7.0
hyperframe==6.0.0
idna==2.7
imageai==2.1.6
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1594044661732/work
imagesize==1.2.0
imgviz==1.2.5
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1602263269022/work
iniconfig @ file:///tmp/build/80754af9/iniconfig_1602780191262/work
intake==0.6.1
intake-stac==0.3.0
intake-xarray==0.4.1
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///tmp/build/80754af9/ipykernel_1596207638929/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipyleaflet==0.13.6
ipython @ file:///tmp/build/80754af9/ipython_1604101197014/work
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort @ file:///home/conda/feedstock_root/build_artifacts/isort_1602591728846/work
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///tmp/build/80754af9/jedi_1592841866100/work
jeepney @ file:///tmp/build/80754af9/jeepney_1605069705079/work
Jinja2==2.11.2
jmespath==0.10.0
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1601671685479/work
json5==0.9.5
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/work
jupyter==1.0.0
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1598486169312/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1598728807792/work
jupyter-core==4.6.3
jupyterlab==2.2.6
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
jupyterlab-widgets==1.0.0
kaleido==0.2.1
keplergl==0.2.2
Keras==2.4.3
keras-resnet==0.2.0
keyring @ file:///tmp/build/80754af9/keyring_1601490835422/work
keyrings.alt @ file:///home/conda/feedstock_root/build_artifacts/keyrings.alt_1608136994844/work
kiwisolver @ file:///tmp/build/80754af9/kiwisolver_1604014535162/work
labelImg==1.8.5
labelme==4.5.7
landsatxplore==0.8
lazy-object-proxy==1.4.3
libarchive-c==2.9
llvmlite==0.34.0
locket==0.2.0
lockfile==0.12.2
locust==1.5.3
lxml @ file:///tmp/build/80754af9/lxml_1603216285000/work
Markdown==3.3.4
MarkupSafe==1.1.1
marshmallow==3.12.1
marshmallow-enum==1.5.1
matplotlib==3.3.2
mccabe==0.6.1
mercantile==1.2.1
mistune==0.8.4
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
mock==4.0.2
mongoengine==0.20.0
more-itertools @ file:///tmp/build/80754af9/more-itertools_1605111547926/work
motor==2.4.0
mpmath==1.1.0
msal==1.11.0
msgpack==1.0.0
multidict==5.1.0
multipledispatch==0.6.0
munch==2.5.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1602859080374/work
nbconvert @ file:///tmp/build/80754af9/nbconvert_1601914830498/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1602732862338/work
ndjson==0.3.1
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1605115881283/work
netCDF4==1.5.5.1
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1598210780226/work
nine==1.1.0
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
nodeeditor==0.9.12
nodejs==0.1.1
nose==1.3.7
notebook @ file:///tmp/build/80754af9/notebook_1601501575118/work
notify-run==0.0.13
numba @ file:///tmp/build/80754af9/numba_1600100669015/work
numcodecs==0.7.3
numexpr==2.7.1
numpy==1.19.3
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauthlib==3.1.1
Office365-REST-Python-Client==2.3.3
olefile==0.46
opencv-python==4.3.0.36
opencv-python-headless==4.4.0.46
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1598029012711/work
openTSNE @ file:///home/conda/feedstock_root/build_artifacts/opentsne_1604248201292/work
optional-django==0.1.0
orange-canvas-core @ file:///home/conda/feedstock_root/build_artifacts/orange-canvas-core_1612536735247/work
orange-widget-base @ file:///home/conda/feedstock_root/build_artifacts/orange-widget-base_1613751231754/work
Orange3 @ file:///tmp/build/80754af9/orange3_1594070640761/work
orjson==3.5.1
osgeo==0.0.0
packaging==20.4
paho-mqtt==1.5.1
pandas @ file:///tmp/build/80754af9/pandas_1602088120436/work
pandocfilters @ file:///tmp/build/80754af9/pandocfilters_1605120460739/work
panel==0.10.3
param==1.10.1
parso==0.7.0
partd==1.1.0
path @ file:///tmp/build/80754af9/path_1598376507494/work
pathlib2==2.3.5
pathtools==0.1.2
patool==1.12
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.1
pivottablejs==0.9.0
pkginfo==1.6.1
planet==1.4.6
plotly==5.1.0
pluggy==0.13.1
ply==3.11
pprintpp==0.4.0
prometheus-client==0.8.0
promise==2.3
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1602524994744/work
psutil @ file:///tmp/build/80754af9/psutil_1598370257551/work
psycopg2==2.8.6
psycopg2-binary==2.8.6
ptyprocess==0.6.0
pushpad==0.9.0
py @ file:///tmp/build/80754af9/py_1593446248552/work
py-vapid==1.8.1
py7zr==0.11.0
pycodestyle==2.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycrypto==2.6.1
pycryptodome==3.9.9
pyct==0.4.8
pycurl==7.43.0.6
pydantic==1.8.1
pydocstyle @ file:///home/conda/feedstock_root/build_artifacts/pydocstyle_1598747747227/work
pyelliptic==1.5.7
pyepsg==0.4.0
pyflakes==2.2.0
PyFlow @ git+https://github.com/wonderworks-software/PyFlow.git@57e2c858933bf63890d769d985396dfad0fca0f0
Pygments @ file:///tmp/build/80754af9/pygments_1604103097372/work
PyJWT==2.1.0
pylint @ file:///tmp/build/80754af9/pylint_1598623985952/work
pymongo==3.12.0
pymsteams==0.1.14
PyMySQL==0.9.3
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyproj==3.0.0.post1
PyQRCode==1.2.1
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqtgraph @ file:///home/conda/feedstock_root/build_artifacts/pyqtgraph_1608440585394/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141720057/work
pyshp==2.1.3
PySide2==5.15.2
PySocks==1.7.1
pystac==0.5.4
pytest==0.0.0
python-dateutil==2.7.5
python-dotenv==0.17.0
python-jose==0.6.1
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///home/conda/feedstock_root/build_artifacts/python-language-server_1600306384607/work
python-louvain @ file:///home/conda/feedstock_root/build_artifacts/python-louvain_1609125227889/work
python-multipart==0.0.5
pytz==2020.1
pyvips==2.1.8
pyviz-comms==2.0.1
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658317819/work
pywebpush==1.13.0
pyxdg @ file:///tmp/build/80754af9/pyxdg_1603822279816/work
PyYAML==5.3.1
pyzmq==19.0.2
qasync @ file:///home/conda/feedstock_root/build_artifacts/qasync_1611997537592/work
QDarkStyle==2.8.1
qgrid==1.3.1
Qt.py==1.3.5
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
rasterio==1.1.8
regex @ file:///tmp/build/80754af9/regex_1602786672676/work
requests==2.25.1
requests-futures==0.9.7
requests-oauthlib==1.3.0
retrying==1.3.3
rfc3986 @ file:///home/conda/feedstock_root/build_artifacts/rfc3986_1593217945888/work
rioxarray==0.3.1
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
Rtree==0.9.4
ruamel-yaml==0.15.87
Rx==1.6.1
ryvencore-qt==0.0.2.8
s3transfer==0.4.2
sat-search==0.3.0
sat-stac==0.4.1
scikit-image==0.17.2
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1598376899566/work
scipy==1.4.1
seaborn @ file:///tmp/build/80754af9/seaborn_1600553570093/work
SecretStorage==3.1.2
Send2Trash==1.5.0
sentinelhub==3.3.1
sentinelsat==0.14
serverfiles==0.3.0
Shapely==1.7.1
shiboken2==5.15.2
simplegeneric==0.8.1
singledispatch @ file:///tmp/build/80754af9/singledispatch_1602523705405/work
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1605205327372/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1610318319305/work
snowballstemmer==2.0.0
snuggs==1.4.7
sortedcollections==1.2.1
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1597405755328/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///tmp/build/80754af9/spyder_1599056981321/work
spyder-kernels @ file:///tmp/build/80754af9/spyder-kernels_1599056754858/work
SQLAlchemy==1.4.0
starlette==0.13.6
statsmodels @ file:///tmp/build/80754af9/statsmodels_1602280205159/work
stringcase==1.2.0
sympy @ file:///tmp/build/80754af9/sympy_1605119542615/work
tables==3.6.1
tabulate==0.8.9
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
tenacity==8.0.1
termcolor==1.1.0
terminado==0.9.1
terracotta==0.7.2
testpath==0.4.4
texttable==1.6.3
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
tifffile==2020.10.1
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1600973991856/work
torch==1.8.1
torchvision==0.9.1
tornado==6.0.4
tqdm @ file:///tmp/build/80754af9/tqdm_1602185206534/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1602771532708/work
traittypes==0.2.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
typing-inspect==0.7.1
tzlocal==2.1
ujson==3.2.0
unicodecsv==0.14.1
universal-analytics-python3==1.1.1
urllib3==1.26.6
utm==0.7.0
uvicorn==0.13.4
uvloop==0.15.2
voxel51-eta==0.5.1
watchdog @ file:///tmp/build/80754af9/watchdog_1593447344699/work
watchgod==0.7
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webcolors==1.11.1
webencodings==0.5.1
websockets==8.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.11.2
wurlitzer @ file:///tmp/build/80754af9/wurlitzer_1594753850195/work
xarray==0.16.2
xlrd==1.2.0
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1602692860603/work
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
yarl==1.6.3
zarr==2.6.1
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work
zope.event==4.5.0
zope.interface @ file:///tmp/build/80754af9/zope.interface_1602002420968/work

**Comment by dionhaefner** [comment]
This is a version conflict between `marshmallow` and `apispec`. Easiest fix should be

```bash
$ pip install -U marshmallow
```

Let me know if that works for you.

**Comment by monkknacky** [comment]
Works! Thank you.
