### ISSUE TITLE
RGB GeoTIFFs??

### ISSUE THREAD

**Issue by antonkarasu** [DHI-GRAS/terracotta#237]
I can find no documentation on this; is it possible to use RGB GeoTIFFs? I see some implementations using multiple files - one for each band, but is there an alternative?

**Comment by dionhaefner** [comment]
No, one file for each band is the correct way to handle this. It should be easy to split your RGB GTiffs with GDAL or rasterio, but if you have a good suggestion to handle this with Terracotta I'm all ears.

**Comment by dionhaefner** [comment]
I guess this is answered.
