### ISSUE TITLE
Use SQLAlchemy for SQL drivers?

### ISSUE THREAD

**Issue by nickeopti** [DHI-GRAS/terracotta#238]
Opinions on using SQLAlchemy to combine the terracotta SQL drivers?

It seems to eliminate the need for two almost identical files, `drivers/mysql.py` and `drivers/sqlite`, and make it easy to allow for a PostgreSQL driver as well.

Are there some disadvantages discouraging the change?
It will of course add an extra dependency -- how bad is that?

@dionhaefner @j08lue 
References #76.

**Comment by dionhaefner** [comment]
Sounds reasonable to me :) If you can make all the tests pass I would be happy to merge this.

**Comment by nickeopti** [comment]
Cool :) I'm not quite ready to begin yet (and I honestly don't know SQLAlchemy well enough to know how big a challenge it will be), but I'll add it to my to-do list then
