### ISSUE TITLE
Internal reliance on physical order of DB rows

### ISSUE THREAD

**Issue by nickeopti** [DHI-GRAS/terracotta#241]
Many of the methods in the database drivers allow input as an ordered sequence of values -- which shall correspond to the order of the keys in `driver.key_names`, which is again assumed to always be in the same order as they originally were, when the database was created. See eg
https://github.com/DHI-GRAS/terracotta/blob/main/terracotta/drivers/mysql.py#L429, and
https://github.com/DHI-GRAS/terracotta/blob/main/terracotta/drivers/mysql.py#L476

However, as far as I can tell, we actually have no guarantee that the order of `key_names` itself is consistent. If the order changes, most of the code relying on sequence inputs will fail.
The keys are retrieved by a simple `SELECT * FROM key_names`:
https://github.com/DHI-GRAS/terracotta/blob/main/terracotta/drivers/mysql.py#L327

But such `SELECT` statements (without an `ORDER BY` clause) have no inherent guarantees of the order of the returned rows. They are in essence unordered set-operations -- which just happen to generally return the rows in the order that they were inserted in, as that is the fastest way to "physically" read them from disk.

I stumbled into this while implementing the new SQLAlchemy branch, because SA seems to deliberately change the order of inserted rows. I don't know whether we've actually ever encountered that the "physical" order was not reflected in the `driver.key_names` -- but I think relying on that order is a bit risky. In other words, I believe this is a potential problem, even though we may never have encountered it.

Proposals to fix:
 a) Disallow ordered sequences as inputs -- require a key-value based mapping as input, or
 b) Save the intended order of the keys in the database, in an extra `index` column on the `key_names` table.

I think option b) is the simplest to implement, and the one preserving the current user-functionality of the application. So I think that probably is the way to go. I fact, I solved the ordering-problems I encountered in the SQLAlchemy branch by introducing such an extra column, and then retrieving the keys by `SELECT key_name, description FROM key_names ORDER BY index`.

Next question is whether we shall rush to implement that fix in the current version now, or cross our fingers and hope for the best until the new SQLAlchemy approach is fully implemented?

**Comment by dionhaefner** [comment]
> I think option b) is the simplest to implement, and the one preserving the current user-functionality of the application. So I think that probably is the way to go.

Agreed.

> Next question is whether we shall rush to implement that fix in the current version now, or cross our fingers and hope for the best until the new SQLAlchemy approach is fully implemented?

Up to you, if you can make the current tests pass without changes it's fine for now.
