### ISSUE TITLE
PNG Tiles with DEM Format

### ISSUE THREAD

**Issue by zufryy** [DHI-GRAS/terracotta#275]
Hi All,

I plan to use the PNG tiles from terracotta as input for gloperations leaflet plugins.
Instead of the PNG with colormap based on range output, is it possible to have an output that follows the DEM encoding for elevation data `height = -10000 + (((R * 256 * 256)+ (G *256) + B) *0.1)` ?

Thank you in advance.

**Comment by dionhaefner** [comment]
You can use the `/compute` API endpoint to do this. Please check `/apidoc` on your Terracotta server for available options.

If you want better performance it might pay off to compute the elevation ahead of time though and ingest that as a separate singleband raster.
