### ISSUE TITLE
Postgres driver ignores supplied database name

### ISSUE THREAD

**Issue by bartwalczak** [DHI-GRAS/terracotta#290]
The offending line seems to be here:
https://github.com/DHI-GRAS/terracotta/blob/964a72b022bea565a10a73d6cce0a40542304a90/terracotta/drivers/postgresql_meta_store.py#L67
```
       engine = sqla.create_engine(
            # `.set()` returns a copy with changed parameters
            self.url.set(database=self.DEFAULT_CONNECT_DB),
            echo=False,
            future=True,
            isolation_level='AUTOCOMMIT'
        )
```

The supplied name is replaced with `DEFAULT_CONNECT_DB`.

**Comment by dionhaefner** [comment]
Can you tell us what you're trying to do / what kind of error you get? That line is fine - using the default DB is intended behavior here because the target DB doesn't exist yet.

**Comment by bartwalczak** [comment]
You're right, I misunderstood the functionality of `set`. I thought it also changed the underlying class property. Apologies.
