### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by ecomodeller** [DHI-GRAS/terracotta#301]
https://terracotta-python.readthedocs.io/en/latest/tutorials/windows.html#setting-up-a-terracotta-environment-on-windows-10

Since most people running Windows are on Windows 11, this page might be a bit confusing.

Does it only apply if you are on Win 10, or is it Windows in general, Windows 10 and above??

**Comment by j08lue** [comment]
Yeah, this is pretty Python-generic info to help out poor souls having to do dev work on Windows. ;-) I'd say we can just drop the version and see whether we get any Vista users complaining.

The WSL guidelines could get outdated, though, but I'd say just drop the version and take it from there.

PRs welcome! :-D
