### ISSUE TITLE
Compatibility with Numpy 1.24

### ISSUE THREAD

**Issue by rbuffat** [DHI-GRAS/terracotta#303]
Terracotta v0.7.5 uses np.object, which [was removed in NumPy 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html). This is already fixed in main, but it would be nice if a new release could be made.

**Comment by dionhaefner** [comment]
Fixed (just released v0.8.0)

**Comment by rbuffat** [comment]
Thanks @dionhaefner !
